services:
  memgraph:
    image: memgraph/memgraph-mage:latest
    container_name: memgraph-mage
    ports:
      - "7687:7687"
      - "7444:7444"
    command: ["--log-level=TRACE", "--schema-info-enabled=true"]
    volumes:
      - memgraph_data:/var/lib/memgraph
    healthcheck:
      test: ["CMD", "echo", "RETURN 1;", "|", "mgconsole"]
      interval: 10s
      timeout: 5s
      retries: 5

  lab:
    image: memgraph/lab:latest
    container_name: memgraph-lab
    ports:
      - "3000:3000"
    depends_on:
      memgraph:
        condition: service_healthy
    environment:
      - QUICK_CONNECT_MG_HOST=memgraph
      - QUICK_CONNECT_MG_PORT=7687

volumes:
  memgraph_data:
